[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variable settings - add your actual values in the Netlify dashboard
[build.environment]

# Production context: all deploys from the main branch
[context.production]
  command = "npm run build"

# Deploy preview context: deploy previews (PRs)
[context.deploy-preview]
  command = "npm run build"

# For client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
